--- #YAML:1.0
name:               Tie-Watch
version:            1.301
abstract:           Place watchpoints on Perl (and Tk) variables
author:
    - Steve Lidie (Stephen.O.Lidie@Lehigh.EDU)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    repository:  git://github.com/eserte/Tie-Watch.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
